apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: joadithya/ecomm-auth
      context: .
      docker:
        dockerfile: apps/auth/Dockerfile
      sync:
        manual:
          - src: 'apps/auth/src/**/*.ts'
            dest: .
          - src: 'libs/server/**/*.ts'
            dest: .
    - image: joadithya/ecomm-products
      context: .
      docker:
        dockerfile: apps/products/Dockerfile
      sync:
        manual:
          - src: 'apps/products/src/**/*.ts'
            dest: .
          - src: 'libs/server/**/*.ts'
            dest: .
    - image: joadithya/ecomm-orders
      context: .
      docker:
        dockerfile: apps/orders/Dockerfile
      sync:
        manual:
          - src: 'apps/orders/src/**/*.ts'
            dest: .
          - src: 'libs/server/**/*.ts'
            dest: .
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*