apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: joadithya/ecomm-auth
      context: .
      docker:
        dockerfile: apps/auth/Dockerfile
        buildArgs:
          TARGET: development
      sync:
        manual:
          - src: 'apps/auth/src/**/*.ts'
            dest: .
          - src: 'libs/server/**/*.ts'
            dest: .
    - image: joadithya/ecomm-products
      context: .
      docker:
        dockerfile: apps/products/Dockerfile
        buildArgs:
          TARGET: development
      sync:
        manual:
          - src: 'apps/products/src/**/*.ts'
            dest: .
          - src: 'libs/server/**/*.ts'
            dest: .
    - image: joadithya/ecomm-orders
      context: .
      docker:
        dockerfile: apps/orders/Dockerfile
        buildArgs:
          TARGET: development
      sync:
        manual:
          - src: 'apps/orders/src/**/*.ts'
            dest: .
          - src: 'libs/server/**/*.ts'
            dest: .
    - image: joadithya/ecomm-expiration
      context: .
      docker:
        dockerfile: apps/expiration/Dockerfile
        buildArgs:
          TARGET: production
      sync:
        manual:
          - src: 'apps/expiration/src/**/*.ts'
            dest: .
          - src: 'libs/server/**/*.ts'
            dest: .
    - image: joadithya/ecomm-payments
      context: .
      docker:
        dockerfile: apps/payments/Dockerfile
        buildArgs:
          TARGET: development
      sync:
        manual:
          - src: 'apps/payments/src/**/*.ts'
            dest: .
          - src: 'libs/server/**/*.ts'
            dest: .
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*