apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-db
  template:
    metadata:
      labels:
        app: payments-db
    spec:
      containers:
        - name: payments-db
          image: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: payments-secret
                  key: POSTGRES_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: payments-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payments-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: payments-db-svc
spec:
  selector:
    app: payments-db
  ports:
    - name: payments-db
      protocol: TCP
      port: 5432
